// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8vOX4JtAsKuwr_3F7ncmnNiCdEle9CNA',
    appId: '1:370069966866:web:dce641a121ea7c629748cb',
    messagingSenderId: '370069966866',
    projectId: 'blood-donate-856e3',
    authDomain: 'blood-donate-856e3.firebaseapp.com',
    storageBucket: 'blood-donate-856e3.appspot.com',
    measurementId: 'G-091QYPM855',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaNRZmY589jctc6SR8LQ6ZDrYanjJWuG8',
    appId: '1:370069966866:android:3f67a9dce705ebeb9748cb',
    messagingSenderId: '370069966866',
    projectId: 'blood-donate-856e3',
    storageBucket: 'blood-donate-856e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALORG-Xn9TSi9CW-ZCW_PBnwgmjp9VbUs',
    appId: '1:370069966866:ios:6c332ec14342dbcb9748cb',
    messagingSenderId: '370069966866',
    projectId: 'blood-donate-856e3',
    storageBucket: 'blood-donate-856e3.appspot.com',
    iosBundleId: 'com.dumatatech.blooddonate.bloodDonate',
  );
}
